const COLLECTIONS = {
  POSSIBLE_RAW_MATERIALS: "possible_raw_materials",
  RAW_MATERIALS_STOCK: "raw_materials_stock",
  RAW_MATERIALS_HISTORY: "raw_materials_history",
  PRODUCT_FORMULAS: "product_formulas",
  PRODUCTION_REQUESTS: "production_requests"
};

const HISTORY_ACTION_TYPES = {
  NEW_STOCK: "NEW_STOCK",
  USED_FOR_PRODUCTION: "USED_FOR_PRODUCTION",
  PRODUCTION_CANCELLATION: "PRODUCTION_CANCELLATION",
  RESTOCKED_AFTER_CANCEL: "RESTOCKED_AFTER_CANCEL"
};

const CHANGE_DIRECTIONS = {
  INCREASE: "INCREASE",
  DECREASE: "DECREASE"
};

const PRODUCTION_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
  CANCELED: "CANCELED",
  SHIPPED: "SHIPPED"
};

const VALID_STATUS_TRANSITIONS = {
  REQUESTED: ["APPROVED", "DECLINED"],
  APPROVED: ["IN_PROGRESS"],
  DECLINED: [], // terminal state
  IN_PROGRESS: ["DONE", "CANCELED"],
  DONE: ["SHIPPED"],
  CANCELED: [],
  SHIPPED: [] // terminal state
};

module.exports = {
  COLLECTIONS,
  HISTORY_ACTION_TYPES,
  CHANGE_DIRECTIONS,
  PRODUCTION_STATUS,
  VALID_STATUS_TRANSITIONS
};
