const COLLECTIONS = {
  POSSIBLE_RAW_MATERIALS: "possible_raw_materials",
  RAW_MATERIALS_STOCK: "raw_materials_stock",
  RAW_MATERIALS_HISTORY: "raw_materials_history",
  PRODUCT_FORMULAS: "product_formulas",
  PRODUCTION_REQUESTS: "production_requests"
};

const HISTORY_ACTION_TYPES = {
  NEW_STOCK: "NEW_STOCK",
  USED_FOR_PRODUCTION: "USED_FOR_PRODUCTION",
  PRODUCTION_CANCELLATION: "PRODUCTION_CANCELLATION",
  RESTOCKED_AFTER_CANCEL: "RESTOCKED_AFTER_CANCEL"
};

const CHANGE_DIRECTIONS = {
  INCREASE: "INCREASE",
  DECREASE: "DECREASE"
};

const PRODUCTION_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
  SHIPPED: "SHIPPED"
};

const VALID_STATUS_TRANSITIONS = {
  [PRODUCTION_STATUS.REQUESTED]: [PRODUCTION_STATUS.APPROVED, PRODUCTION_STATUS.DECLINED],
  [PRODUCTION_STATUS.APPROVED]: [PRODUCTION_STATUS.IN_PROGRESS, PRODUCTION_STATUS.CANCELED],
  [PRODUCTION_STATUS.IN_PROGRESS]: [PRODUCTION_STATUS.COMPLETED, PRODUCTION_STATUS.CANCELED],
  [PRODUCTION_STATUS.COMPLETED]: [PRODUCTION_STATUS.SHIPPED],
  [PRODUCTION_STATUS.DECLINED]: [],
  [PRODUCTION_STATUS.CANCELED]: [],
  [PRODUCTION_STATUS.SHIPPED]: []
};

module.exports = {
  COLLECTIONS,
  HISTORY_ACTION_TYPES,
  CHANGE_DIRECTIONS,
  PRODUCTION_STATUS,
  VALID_STATUS_TRANSITIONS
};
